import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/mainpagewithaccount">MainPageWithAccount</Link>
        </li>
        <li>
          <Link to="/mainpagenoaccount">MainPageNoAccount</Link>
        </li>
        <li>
          <Link to="/searcha">SearchA</Link>
        </li>
        <li>
          <Link to="/searchafiltername">SearchAFilterName</Link>
        </li>
        <li>
          <Link to="/searchafilterlowest">SearchAFilterLowest</Link>
        </li>
        <li>
          <Link to="/searchafilterhighest">SearchAFilterHighest</Link>
        </li>
        <li>
          <Link to="/frontpage">FrontPage</Link>
        </li>
        <li>
          <Link to="/storeratepagewithaccount">StoreRatePageWithAccount</Link>
        </li>
        <li>
          <Link to="/searchwalmart">SearchWalmart</Link>
        </li>
        <li>
          <Link to="/storeratehistoricalpagewithaccount">
            StoreRateHistoricalPageWithAccount
          </Link>
        </li>
        <li>
          <Link to="/splashpage">SplashPage</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
